# syntax=docker.io/docker/dockerfile:1@sha256:2780b5c3bab67f1f76c781860de469442999ed1a0d7992a5efdf2cffc0e3d769
# check=error=true
# Generated by https://github.com/fenollp/supergreen v0.26.0

FROM --platform=$BUILDPLATFORM docker.io/tonistiigi/xx:1.6.1@sha256:923441d7c25f1e2eb5789f82d987693c47b8ed987c4ab3b075d6ed2b5d6779a3 AS xx
FROM scratch AS rustup-1.94.0-x86_64-unknown-linux-gnu
ADD --chmod=0144 --checksum=sha256:4acc9acc76d5079515b46346a485974457b5a79893cfb01112423c89aeb5aa10 \
  https://static.rust-lang.org/rustup/archive/1.29.0/x86_64-unknown-linux-gnu/rustup-init /rustup-init
FROM --platform=$BUILDPLATFORM docker.io/library/debian:trixie-slim@sha256:cedb1ef40439206b673ee8b33a46a03a0c9fa90bf3732f54704f99cb061d2c5a AS rust-base
SHELL ["/bin/sh", "-eux", "-c"]
ENV       CARGO_HOME=/usr/local/cargo \
         RUSTUP_HOME=/usr/local/rustup \
    RUSTUP_TOOLCHAIN=1.94.0-x86_64-unknown-linux-gnu
ENV CARGO=$RUSTUP_HOME/toolchains/$RUSTUP_TOOLCHAIN/bin/cargo \
    RUSTC=$RUSTUP_HOME/toolchains/$RUSTUP_TOOLCHAIN/bin/rustc \
     PATH=$CARGO_HOME/bin:$PATH
RUN \
  --mount=from=rustup-1.94.0-x86_64-unknown-linux-gnu,source=/rustup-init,dst=/rustup-init \
    set -eux \
 && /rustup-init --verbose -y --no-modify-path --profile minimal --default-toolchain 1.94.0-x86_64-unknown-linux-gnu --default-host x86_64-unknown-linux-gnu \
 && chmod -R a+w $RUSTUP_HOME $CARGO_HOME
ARG TARGETPLATFORM
RUN \
  --mount=from=xx,source=/usr/bin/xx-apk,dst=/usr/bin/xx-apk \
  --mount=from=xx,source=/usr/bin/xx-apt,dst=/usr/bin/xx-apt-get \
  --mount=from=xx,source=/usr/bin/xx-cc,dst=/usr/bin/xx-c++ \
  --mount=from=xx,source=/usr/bin/xx-cargo,dst=/usr/bin/xx-cargo \
  --mount=from=xx,source=/usr/bin/xx-cc,dst=/usr/bin/xx-cc \
  --mount=from=xx,source=/usr/bin/xx-cc,dst=/usr/bin/xx-clang \
  --mount=from=xx,source=/usr/bin/xx-cc,dst=/usr/bin/xx-clang++ \
  --mount=from=xx,source=/usr/bin/xx-go,dst=/usr/bin/xx-go \
  --mount=from=xx,source=/usr/bin/xx-info,dst=/usr/bin/xx-info \
  --mount=from=xx,source=/usr/bin/xx-ld-shas,dst=/usr/bin/xx-ld-shas \
  --mount=from=xx,source=/usr/bin/xx-verify,dst=/usr/bin/xx-verify \
  --mount=from=xx,source=/usr/bin/xx-windres,dst=/usr/bin/xx-windres \
    set -eux \
 && if command -v apk >/dev/null 2>&1; then \
                                                          xx-apk     add     --no-cache                 'ca-certificates' 'gcc'; \
    else \
      xx-apt-get update && DEBIAN_FRONTEND=noninteractive xx-apt-get satisfy --no-install-recommends -y 'build-essential' 'ca-certificates' 'ccache' 'clang' 'cmake' 'curl' 'g++' 'gcc' 'git' 'gperf' 'gstreamer1.0-libav' 'gstreamer1.0-plugins-bad' 'gstreamer1.0-plugins-base' 'gstreamer1.0-plugins-good' 'gstreamer1.0-plugins-ugly' 'gstreamer1.0-tools' 'libc6-dev' 'libdbus-1-dev' 'libegl1-mesa-dev' 'libfreetype6-dev' 'libges-1.0-dev' 'libgl1-mesa-dri' 'libgles2-mesa-dev' 'libglib2.0-dev' 'libgstreamer-plugins-bad1.0-dev' 'libgstreamer-plugins-base1.0-dev' 'libgstrtspserver-1.0-dev' 'libharfbuzz-dev' 'liblzma-dev' 'libudev-dev' 'libunwind-dev' 'libvulkan1' 'libx11-dev' 'libxcb-render0-dev' 'libxcb-shape0-dev' 'libxcb-xfixes0-dev' 'libxkbcommon-x11-0' 'libxkbcommon0' 'libxmu-dev' 'libxmu6' 'llvm-dev' 'm4' 'xorg-dev'; \
    fi
ARG SOURCE_DATE_EPOCH=42


FROM scratch AS cratesio-find-msvc-tools-0.1.9
ADD --chmod=0664 --unpack --checksum=sha256:5baebc0774151f905a1a2cc41989300b1e6fbb29aff0ceffa1064fdd3088d582 \
  https://static.crates.io/crates/find-msvc-tools/find-msvc-tools-0.1.9.crate /
FROM rust-base AS dep-n-find-msvc-tools-0.1.9-03bc48596003a6dc
WORKDIR /target/release/deps
RUN \
  --mount=from=cratesio-find-msvc-tools-0.1.9,source=/find-msvc-tools-0.1.9,dst=$CARGO_HOME/registry/src/index.crates.io/find-msvc-tools-0.1.9 \
    env CARGO_CRATE_NAME=find_msvc_tools \
        CARGO_INCREMENTAL=0 \
        CARGO_MANIFEST_DIR=$CARGO_HOME/registry/src/index.crates.io/find-msvc-tools-0.1.9 \
        CARGO_MANIFEST_PATH=$CARGO_HOME/registry/src/index.crates.io/find-msvc-tools-0.1.9/Cargo.toml \
        CARGO_PKG_AUTHORS= \
        CARGO_PKG_DESCRIPTION=Find' windows-specific tools, read MSVC versions from the registry and from COM interfaces' \
        CARGO_PKG_HOMEPAGE= \
        CARGO_PKG_LICENSE=MIT' OR Apache-2.0' \
        CARGO_PKG_LICENSE_FILE= \
        CARGO_PKG_NAME=find-msvc-tools \
        CARGO_PKG_README=README.md \
        CARGO_PKG_REPOSITORY=https'://github.com/rust-lang/cc-rs' \
        CARGO_PKG_RUST_VERSION=1.63 \
        CARGO_PKG_VERSION=0.1.9 \
        CARGO_PKG_VERSION_MAJOR=0 \
        CARGO_PKG_VERSION_MINOR=1 \
        CARGO_PKG_VERSION_PATCH=9 \
        CARGO_PKG_VERSION_PRE= \
        CARGOGREEN=1 \
      rustc --allow unexpected_cfgs --cap-lints warn --check-cfg cfg'(disable_clang_cl_tests)' --check-cfg cfg'(docsrs,test)' --check-cfg cfg'(feature, values())' --crate-name find_msvc_tools --crate-type lib --edition 2018 --emit dep-info,metadata,link --error-format json --json diagnostic-rendered-ansi,artifacts,future-incompat --out-dir /target/release/deps -C embed-bitcode'=no' -C extra-filename'=-03bc48596003a6dc' -C metadata'=326a04f14d565698' -C overflow-checks'=off' -C strip'=debuginfo' -L dependency'=/target/release/deps' $CARGO_HOME/registry/src/index.crates.io/find-msvc-tools-0.1.9/src/lib.rs \
        1>          ./out-03bc48596003a6dc-stdout \
        2>          ./out-03bc48596003a6dc-stderr \
        || echo $? >./out-03bc48596003a6dc-errcode\
  ; find ./*-03bc48596003a6dc* -exec touch --no-dereference --date=@$SOURCE_DATE_EPOCH '{}' + \
 || echo $? >./out-03bc48596003a6dc-errcode
FROM scratch AS out-03bc48596003a6dc
COPY --link --from=dep-n-find-msvc-tools-0.1.9-03bc48596003a6dc /target/release/deps/*-03bc48596003a6dc* /

FROM scratch AS cratesio-libc-0.2.184
ADD --chmod=0664 --unpack --checksum=sha256:48f5d2a454e16a5ea0f4ced81bd44e4cfc7bd3a507b61887c99fd3538b28e4af \
  https://static.crates.io/crates/libc/libc-0.2.184.crate /
FROM rust-base AS dep-x-libc-0.2.184-6f1993c947aa820c
WORKDIR /target/release/build/libc-6f1993c947aa820c
RUN \
  --mount=from=cratesio-libc-0.2.184,source=/libc-0.2.184,dst=$CARGO_HOME/registry/src/index.crates.io/libc-0.2.184 \
    env CARGO_CRATE_NAME=build_script_build \
        CARGO_INCREMENTAL=0 \
        CARGO_MANIFEST_DIR=$CARGO_HOME/registry/src/index.crates.io/libc-0.2.184 \
        CARGO_MANIFEST_PATH=$CARGO_HOME/registry/src/index.crates.io/libc-0.2.184/Cargo.toml \
        CARGO_PKG_AUTHORS=The' Rust Project Developers' \
        CARGO_PKG_DESCRIPTION=Raw' FFI bindings to platform libraries like libc.' \
        CARGO_PKG_HOMEPAGE= \
        CARGO_PKG_LICENSE=MIT' OR Apache-2.0' \
        CARGO_PKG_LICENSE_FILE= \
        CARGO_PKG_NAME=libc \
        CARGO_PKG_README=README.md \
        CARGO_PKG_REPOSITORY=https'://github.com/rust-lang/libc' \
        CARGO_PKG_RUST_VERSION=1.65 \
        CARGO_PKG_VERSION=0.2.184 \
        CARGO_PKG_VERSION_MAJOR=0 \
        CARGO_PKG_VERSION_MINOR=2 \
        CARGO_PKG_VERSION_PATCH=184 \
        CARGO_PKG_VERSION_PRE= \
        CARGOGREEN=1 \
      rustc --allow clippy'::expl_impl_clone_on_copy' --allow clippy'::identity_op' --allow clippy'::missing_safety_doc' --allow clippy'::non_minimal_cfg' --allow clippy'::uninlined_format_args' --allow clippy'::unnecessary_cast' --allow clippy'::used_underscore_binding' --allow unused_qualifications --cap-lints warn --cfg feature'="default"' --cfg feature'="std"' --check-cfg cfg'(docsrs,test)' --check-cfg cfg'(feature, values("align", "const-extern-fn", "default", "extra_traits", "rustc-dep-of-std", "rustc-std-workspace-core", "std", "use_std"))' --crate-name build_script_build --crate-type bin --edition 2021 --emit dep-info,link --error-format json --json diagnostic-rendered-ansi,artifacts,future-incompat --out-dir /target/release/build/libc-6f1993c947aa820c --warn clippy'::explicit_iter_loop' --warn clippy'::manual_assert' --warn clippy'::map_unwrap_or' --warn clippy'::ptr_as_ptr' --warn clippy'::unnecessary_semicolon' -C embed-bitcode'=no' -C extra-filename'=-6f1993c947aa820c' -C metadata'=e57d7c2047f2f24f' -C overflow-checks'=off' -C strip'=debuginfo' -L dependency'=/target/release/deps' $CARGO_HOME/registry/src/index.crates.io/libc-0.2.184/build.rs \
        1>          ./out-6f1993c947aa820c-stdout \
        2>          ./out-6f1993c947aa820c-stderr \
        || echo $? >./out-6f1993c947aa820c-errcode\
  ; mv ./build_script_build-6f1993c947aa820c ./_build_script_build-6f1993c947aa820c \
 && printf '#!/bin/sh\nenv CARGOGREEN_EXECUTE_BUILDRS_=$0 cargo-green\n' >./build_script_build-6f1993c947aa820c \
 && chmod +x ./build_script_build-6f1993c947aa820c \
 || echo $? >./out-6f1993c947aa820c-errcode \
  ; find ./* -exec touch --no-dereference --date=@$SOURCE_DATE_EPOCH '{}' + \
 || echo $? >./out-6f1993c947aa820c-errcode
FROM scratch AS out-6f1993c947aa820c
COPY --link --from=dep-x-libc-0.2.184-6f1993c947aa820c /target/release/build/libc-6f1993c947aa820c/*-6f1993c947aa820c* /

FROM rust-base AS run-z-libc-0.2.184-476b580b083ed7c7
WORKDIR /target/release/build/libc-476b580b083ed7c7/out
WORKDIR $CARGO_HOME/registry/src/index.crates.io/libc-0.2.184
RUN \
  --mount=from=out-6f1993c947aa820c,source=/_build_script_build-6f1993c947aa820c,dst=/target/release/build/libc-6f1993c947aa820c/build-script-build \
  --mount=from=cratesio-libc-0.2.184,source=/libc-0.2.184,dst=$CARGO_HOME/registry/src/index.crates.io/libc-0.2.184 \
    env CARGO_CFG_DEBUG_ASSERTIONS= \
        CARGO_CFG_FEATURE=default,std \
        CARGO_CFG_PANIC=unwind \
        CARGO_CFG_TARGET_ABI= \
        CARGO_CFG_TARGET_ARCH=x86_64 \
        CARGO_CFG_TARGET_ENDIAN=little \
        CARGO_CFG_TARGET_ENV=gnu \
        CARGO_CFG_TARGET_FAMILY=unix \
        CARGO_CFG_TARGET_FEATURE=fxsr,sse,sse2 \
        CARGO_CFG_TARGET_HAS_ATOMIC=16,32,64,8,ptr \
        CARGO_CFG_TARGET_OS=linux \
        CARGO_CFG_TARGET_POINTER_WIDTH=64 \
        CARGO_CFG_TARGET_VENDOR=unknown \
        CARGO_CFG_UNIX= \
        CARGO_ENCODED_RUSTFLAGS= \
        CARGO_FEATURE_DEFAULT=1 \
        CARGO_FEATURE_STD=1 \
        CARGO_INCREMENTAL=0 \
        CARGO_MANIFEST_DIR=$CARGO_HOME/registry/src/index.crates.io/libc-0.2.184 \
        CARGO_MANIFEST_PATH=$CARGO_HOME/registry/src/index.crates.io/libc-0.2.184/Cargo.toml \
        CARGO_PKG_AUTHORS=The' Rust Project Developers' \
        CARGO_PKG_DESCRIPTION=Raw' FFI bindings to platform libraries like libc.' \
        CARGO_PKG_HOMEPAGE= \
        CARGO_PKG_LICENSE=MIT' OR Apache-2.0' \
        CARGO_PKG_LICENSE_FILE= \
        CARGO_PKG_NAME=libc \
        CARGO_PKG_README=README.md \
        CARGO_PKG_REPOSITORY=https'://github.com/rust-lang/libc' \
        CARGO_PKG_RUST_VERSION=1.65 \
        CARGO_PKG_VERSION=0.2.184 \
        CARGO_PKG_VERSION_MAJOR=0 \
        CARGO_PKG_VERSION_MINOR=2 \
        CARGO_PKG_VERSION_PATCH=184 \
        CARGO_PKG_VERSION_PRE= \
        DEBUG=false \
        HOST=x86_64-unknown-linux-gnu \
        NUM_JOBS=1 \
        OPT_LEVEL=0 \
        OUT_DIR=/target/release/build/libc-476b580b083ed7c7/out \
        PROFILE=release \
        RUSTDOC=$RUSTUP_HOME/toolchains/1.94.0-x86_64-unknown-linux-gnu/bin/rustdoc \
        TARGET=x86_64-unknown-linux-gnu \
        CARGOGREEN=1 \
      /target/release/build/libc-6f1993c947aa820c/build-script-build \
        1>          /target/release/build/libc-476b580b083ed7c7/out/out-476b580b083ed7c7-stdout \
        2>          /target/release/build/libc-476b580b083ed7c7/out/out-476b580b083ed7c7-stderr \
        || echo $? >/target/release/build/libc-476b580b083ed7c7/out/out-476b580b083ed7c7-errcode\
  ; find /target/release/build/libc-476b580b083ed7c7/out/* -exec touch --no-dereference --date=@$SOURCE_DATE_EPOCH '{}' + \
 || echo $? >/target/release/build/libc-476b580b083ed7c7/out/out-476b580b083ed7c7-errcode
FROM scratch AS out-476b580b083ed7c7
COPY --link --from=run-z-libc-0.2.184-476b580b083ed7c7 /target/release/build/libc-476b580b083ed7c7/out /


FROM rust-base AS dep-n-libc-0.2.184-4ba22a5c4650f7d6
WORKDIR /target/release/deps
RUN \
  --mount=from=cratesio-libc-0.2.184,source=/libc-0.2.184,dst=$CARGO_HOME/registry/src/index.crates.io/libc-0.2.184 \
  --mount=from=out-476b580b083ed7c7,dst=/target/release/build/libc-476b580b083ed7c7/out,source=/ \
    env CARGO_CRATE_NAME=libc \
        CARGO_INCREMENTAL=0 \
        CARGO_MANIFEST_DIR=$CARGO_HOME/registry/src/index.crates.io/libc-0.2.184 \
        CARGO_MANIFEST_PATH=$CARGO_HOME/registry/src/index.crates.io/libc-0.2.184/Cargo.toml \
        CARGO_PKG_AUTHORS=The' Rust Project Developers' \
        CARGO_PKG_DESCRIPTION=Raw' FFI bindings to platform libraries like libc.' \
        CARGO_PKG_HOMEPAGE= \
        CARGO_PKG_LICENSE=MIT' OR Apache-2.0' \
        CARGO_PKG_LICENSE_FILE= \
        CARGO_PKG_NAME=libc \
        CARGO_PKG_README=README.md \
        CARGO_PKG_REPOSITORY=https'://github.com/rust-lang/libc' \
        CARGO_PKG_RUST_VERSION=1.65 \
        CARGO_PKG_VERSION=0.2.184 \
        CARGO_PKG_VERSION_MAJOR=0 \
        CARGO_PKG_VERSION_MINOR=2 \
        CARGO_PKG_VERSION_PATCH=184 \
        CARGO_PKG_VERSION_PRE= \
        OUT_DIR=/target/release/build/libc-476b580b083ed7c7/out \
        CARGOGREEN=1 \
      rustc --allow clippy'::expl_impl_clone_on_copy' --allow clippy'::identity_op' --allow clippy'::missing_safety_doc' --allow clippy'::non_minimal_cfg' --allow clippy'::uninlined_format_args' --allow clippy'::unnecessary_cast' --allow clippy'::used_underscore_binding' --allow unused_qualifications --cap-lints warn --cfg feature'="default"' --cfg feature'="std"' --cfg freebsd12 --check-cfg cfg'(docsrs,test)' --check-cfg cfg'(emscripten_old_stat_abi)' --check-cfg cfg'(espidf_time32)' --check-cfg cfg'(feature, values("align", "const-extern-fn", "default", "extra_traits", "rustc-dep-of-std", "rustc-std-workspace-core", "std", "use_std"))' --check-cfg cfg'(freebsd10)' --check-cfg cfg'(freebsd11)' --check-cfg cfg'(freebsd12)' --check-cfg cfg'(freebsd13)' --check-cfg cfg'(freebsd14)' --check-cfg cfg'(freebsd15)' --check-cfg cfg'(gnu_file_offset_bits64)' --check-cfg cfg'(gnu_time_bits64)' --check-cfg cfg'(libc_deny_warnings)' --check-cfg cfg'(linux_time_bits64)' --check-cfg cfg'(musl32_time64)' --check-cfg cfg'(musl_v1_2_3)' --check-cfg cfg'(target_arch,values("loongarch64","mips32r6","mips64r6","csky"))' --check-cfg cfg'(target_env,values("illumos","wasi","aix","ohos","nto71_iosock","nto80"))' --check-cfg cfg'(target_os,values("switch","aix","ohos","hurd","rtems","visionos","nuttx","cygwin","qurt"))' --check-cfg cfg'(vxworks_lt_25_09)' --crate-name libc --crate-type lib --edition 2021 --emit dep-info,metadata,link --error-format json --json diagnostic-rendered-ansi,artifacts,future-incompat --out-dir /target/release/deps --warn clippy'::explicit_iter_loop' --warn clippy'::manual_assert' --warn clippy'::map_unwrap_or' --warn clippy'::ptr_as_ptr' --warn clippy'::unnecessary_semicolon' -C embed-bitcode'=no' -C extra-filename'=-4ba22a5c4650f7d6' -C metadata'=f64cf15db57f2725' -C overflow-checks'=off' -C strip'=debuginfo' -L dependency'=/target/release/deps' $CARGO_HOME/registry/src/index.crates.io/libc-0.2.184/src/lib.rs \
        1>          ./out-4ba22a5c4650f7d6-stdout \
        2>          ./out-4ba22a5c4650f7d6-stderr \
        || echo $? >./out-4ba22a5c4650f7d6-errcode\
  ; find ./*-4ba22a5c4650f7d6* -exec touch --no-dereference --date=@$SOURCE_DATE_EPOCH '{}' + \
 || echo $? >./out-4ba22a5c4650f7d6-errcode
FROM scratch AS out-4ba22a5c4650f7d6
COPY --link --from=dep-n-libc-0.2.184-4ba22a5c4650f7d6 /target/release/deps/*-4ba22a5c4650f7d6* /

FROM scratch AS cratesio-jobserver-0.1.34
ADD --chmod=0664 --unpack --checksum=sha256:9afb3de4395d6b3e67a780b6de64b51c978ecf11cb9a462c66be7d4ca9039d33 \
  https://static.crates.io/crates/jobserver/jobserver-0.1.34.crate /
FROM rust-base AS dep-n-jobserver-0.1.34-9de29d5c7086d65d
WORKDIR /target/release/deps
RUN \
  --mount=from=cratesio-jobserver-0.1.34,source=/jobserver-0.1.34,dst=$CARGO_HOME/registry/src/index.crates.io/jobserver-0.1.34 \
  --mount=from=out-4ba22a5c4650f7d6,dst=/target/release/deps/liblibc-4ba22a5c4650f7d6.rmeta,source=/liblibc-4ba22a5c4650f7d6.rmeta \
    env CARGO_CRATE_NAME=jobserver \
        CARGO_INCREMENTAL=0 \
        CARGO_MANIFEST_DIR=$CARGO_HOME/registry/src/index.crates.io/jobserver-0.1.34 \
        CARGO_MANIFEST_PATH=$CARGO_HOME/registry/src/index.crates.io/jobserver-0.1.34/Cargo.toml \
        CARGO_PKG_AUTHORS=Alex' Crichton <alex@alexcrichton.com>' \
        CARGO_PKG_DESCRIPTION=An' implementation of the GNU Make jobserver for Rust.\
' \
        CARGO_PKG_HOMEPAGE=https'://github.com/rust-lang/jobserver-rs' \
        CARGO_PKG_LICENSE=MIT' OR Apache-2.0' \
        CARGO_PKG_LICENSE_FILE= \
        CARGO_PKG_NAME=jobserver \
        CARGO_PKG_README=README.md \
        CARGO_PKG_REPOSITORY=https'://github.com/rust-lang/jobserver-rs' \
        CARGO_PKG_RUST_VERSION=1.63 \
        CARGO_PKG_VERSION=0.1.34 \
        CARGO_PKG_VERSION_MAJOR=0 \
        CARGO_PKG_VERSION_MINOR=1 \
        CARGO_PKG_VERSION_PATCH=34 \
        CARGO_PKG_VERSION_PRE= \
        CARGOGREEN=1 \
      rustc --cap-lints warn --check-cfg cfg'(docsrs,test)' --check-cfg cfg'(feature, values())' --crate-name jobserver --crate-type lib --edition 2021 --emit dep-info,metadata,link --error-format json --extern libc'=/target/release/deps/liblibc-4ba22a5c4650f7d6.rmeta' --json diagnostic-rendered-ansi,artifacts,future-incompat --out-dir /target/release/deps -C embed-bitcode'=no' -C extra-filename'=-9de29d5c7086d65d' -C metadata'=15cdee2ce33b4f0f' -C overflow-checks'=off' -C strip'=debuginfo' -L dependency'=/target/release/deps' $CARGO_HOME/registry/src/index.crates.io/jobserver-0.1.34/src/lib.rs \
        1>          ./out-9de29d5c7086d65d-stdout \
        2>          ./out-9de29d5c7086d65d-stderr \
        || echo $? >./out-9de29d5c7086d65d-errcode\
  ; find ./*-9de29d5c7086d65d* -exec touch --no-dereference --date=@$SOURCE_DATE_EPOCH '{}' + \
 || echo $? >./out-9de29d5c7086d65d-errcode
FROM scratch AS out-9de29d5c7086d65d
COPY --link --from=dep-n-jobserver-0.1.34-9de29d5c7086d65d /target/release/deps/*-9de29d5c7086d65d* /

FROM scratch AS cratesio-shlex-1.3.0
ADD --chmod=0664 --unpack --checksum=sha256:0fda2ff0d084019ba4d7c6f371c95d8fd75ce3524c3cb8fb653a3023f6323e64 \
  https://static.crates.io/crates/shlex/shlex-1.3.0.crate /
FROM rust-base AS dep-n-shlex-1.3.0-3b266231d4b893c0
WORKDIR /target/release/deps
RUN \
  --mount=from=cratesio-shlex-1.3.0,source=/shlex-1.3.0,dst=$CARGO_HOME/registry/src/index.crates.io/shlex-1.3.0 \
    env CARGO_CRATE_NAME=shlex \
        CARGO_INCREMENTAL=0 \
        CARGO_MANIFEST_DIR=$CARGO_HOME/registry/src/index.crates.io/shlex-1.3.0 \
        CARGO_MANIFEST_PATH=$CARGO_HOME/registry/src/index.crates.io/shlex-1.3.0/Cargo.toml \
        CARGO_PKG_AUTHORS=comex' <comexk@gmail.com>:Fenhl <fenhl@fenhl.net>:Adrian Taylor <adetaylor@chromium.org>:Alex Touchet <alextouchet@outlook.com>:Daniel Parks <dp+git@oxidized.org>:Garrett Berg <googberg@gmail.com>' \
        CARGO_PKG_DESCRIPTION=Split' a string into shell words, like Python'\'s' shlex.' \
        CARGO_PKG_HOMEPAGE= \
        CARGO_PKG_LICENSE=MIT' OR Apache-2.0' \
        CARGO_PKG_LICENSE_FILE= \
        CARGO_PKG_NAME=shlex \
        CARGO_PKG_README=README.md \
        CARGO_PKG_REPOSITORY=https'://github.com/comex/rust-shlex' \
        CARGO_PKG_RUST_VERSION=1.46.0 \
        CARGO_PKG_VERSION=1.3.0 \
        CARGO_PKG_VERSION_MAJOR=1 \
        CARGO_PKG_VERSION_MINOR=3 \
        CARGO_PKG_VERSION_PATCH=0 \
        CARGO_PKG_VERSION_PRE= \
        CARGOGREEN=1 \
      rustc --cap-lints warn --cfg feature'="default"' --cfg feature'="std"' --check-cfg cfg'(docsrs,test)' --check-cfg cfg'(feature, values("default", "std"))' --crate-name shlex --crate-type lib --edition 2015 --emit dep-info,metadata,link --error-format json --json diagnostic-rendered-ansi,artifacts,future-incompat --out-dir /target/release/deps -C embed-bitcode'=no' -C extra-filename'=-3b266231d4b893c0' -C metadata'=346632f1bcaca4e6' -C overflow-checks'=off' -C strip'=debuginfo' -L dependency'=/target/release/deps' $CARGO_HOME/registry/src/index.crates.io/shlex-1.3.0/src/lib.rs \
        1>          ./out-3b266231d4b893c0-stdout \
        2>          ./out-3b266231d4b893c0-stderr \
        || echo $? >./out-3b266231d4b893c0-errcode\
  ; find ./*-3b266231d4b893c0* -exec touch --no-dereference --date=@$SOURCE_DATE_EPOCH '{}' + \
 || echo $? >./out-3b266231d4b893c0-errcode
FROM scratch AS out-3b266231d4b893c0
COPY --link --from=dep-n-shlex-1.3.0-3b266231d4b893c0 /target/release/deps/*-3b266231d4b893c0* /

FROM scratch AS cratesio-cc-1.2.59
ADD --chmod=0664 --unpack --checksum=sha256:b7a4d3ec6524d28a329fc53654bbadc9bdd7b0431f5d65f1a56ffb28a1ee5283 \
  https://static.crates.io/crates/cc/cc-1.2.59.crate /
FROM rust-base AS dep-n-cc-1.2.59-6c6b7b88f024f856
WORKDIR /target/release/deps
RUN \
  --mount=from=cratesio-cc-1.2.59,source=/cc-1.2.59,dst=$CARGO_HOME/registry/src/index.crates.io/cc-1.2.59 \
  --mount=from=out-03bc48596003a6dc,dst=/target/release/deps/libfind_msvc_tools-03bc48596003a6dc.rmeta,source=/libfind_msvc_tools-03bc48596003a6dc.rmeta \
  --mount=from=out-9de29d5c7086d65d,dst=/target/release/deps/libjobserver-9de29d5c7086d65d.rmeta,source=/libjobserver-9de29d5c7086d65d.rmeta \
  --mount=from=out-4ba22a5c4650f7d6,dst=/target/release/deps/liblibc-4ba22a5c4650f7d6.rmeta,source=/liblibc-4ba22a5c4650f7d6.rmeta \
  --mount=from=out-3b266231d4b893c0,dst=/target/release/deps/libshlex-3b266231d4b893c0.rmeta,source=/libshlex-3b266231d4b893c0.rmeta \
    env CARGO_CRATE_NAME=cc \
        CARGO_INCREMENTAL=0 \
        CARGO_MANIFEST_DIR=$CARGO_HOME/registry/src/index.crates.io/cc-1.2.59 \
        CARGO_MANIFEST_PATH=$CARGO_HOME/registry/src/index.crates.io/cc-1.2.59/Cargo.toml \
        CARGO_PKG_AUTHORS=Alex' Crichton <alex@alexcrichton.com>' \
        CARGO_PKG_DESCRIPTION=A' build-time dependency for Cargo build scripts to assist in invoking the native\
C compiler to compile native C code into a static archive to be linked into Rust\
code.\
' \
        CARGO_PKG_HOMEPAGE=https'://github.com/rust-lang/cc-rs' \
        CARGO_PKG_LICENSE=MIT' OR Apache-2.0' \
        CARGO_PKG_LICENSE_FILE= \
        CARGO_PKG_NAME=cc \
        CARGO_PKG_README=README.md \
        CARGO_PKG_REPOSITORY=https'://github.com/rust-lang/cc-rs' \
        CARGO_PKG_RUST_VERSION=1.63 \
        CARGO_PKG_VERSION=1.2.59 \
        CARGO_PKG_VERSION_MAJOR=1 \
        CARGO_PKG_VERSION_MINOR=2 \
        CARGO_PKG_VERSION_PATCH=59 \
        CARGO_PKG_VERSION_PRE= \
        CARGOGREEN=1 \
      rustc --allow unexpected_cfgs --cap-lints warn --cfg feature'="parallel"' --check-cfg cfg'(disable_clang_cl_tests)' --check-cfg cfg'(docsrs,test)' --check-cfg cfg'(feature, values("jobserver", "parallel"))' --crate-name cc --crate-type lib --edition 2018 --emit dep-info,metadata,link --error-format json --extern find_msvc_tools'=/target/release/deps/libfind_msvc_tools-03bc48596003a6dc.rmeta' --extern jobserver'=/target/release/deps/libjobserver-9de29d5c7086d65d.rmeta' --extern libc'=/target/release/deps/liblibc-4ba22a5c4650f7d6.rmeta' --extern shlex'=/target/release/deps/libshlex-3b266231d4b893c0.rmeta' --json diagnostic-rendered-ansi,artifacts,future-incompat --out-dir /target/release/deps -C embed-bitcode'=no' -C extra-filename'=-6c6b7b88f024f856' -C metadata'=c45a113c82f8dc9b' -C overflow-checks'=off' -C strip'=debuginfo' -L dependency'=/target/release/deps' $CARGO_HOME/registry/src/index.crates.io/cc-1.2.59/src/lib.rs \
        1>          ./out-6c6b7b88f024f856-stdout \
        2>          ./out-6c6b7b88f024f856-stderr \
        || echo $? >./out-6c6b7b88f024f856-errcode\
  ; find ./*-6c6b7b88f024f856* -exec touch --no-dereference --date=@$SOURCE_DATE_EPOCH '{}' + \
 || echo $? >./out-6c6b7b88f024f856-errcode
FROM scratch AS out-6c6b7b88f024f856
COPY --link --from=dep-n-cc-1.2.59-6c6b7b88f024f856 /target/release/deps/*-6c6b7b88f024f856* /

FROM scratch AS cratesio-glob-0.3.3
ADD --chmod=0664 --unpack --checksum=sha256:0cc23270f6e1808e30a928bdc84dea0b9b4136a8bc82338574f23baf47bbd280 \
  https://static.crates.io/crates/glob/glob-0.3.3.crate /
FROM rust-base AS dep-n-glob-0.3.3-e8a15153c90a7f99
WORKDIR /target/release/deps
RUN \
  --mount=from=cratesio-glob-0.3.3,source=/glob-0.3.3,dst=$CARGO_HOME/registry/src/index.crates.io/glob-0.3.3 \
    env CARGO_CRATE_NAME=glob \
        CARGO_INCREMENTAL=0 \
        CARGO_MANIFEST_DIR=$CARGO_HOME/registry/src/index.crates.io/glob-0.3.3 \
        CARGO_MANIFEST_PATH=$CARGO_HOME/registry/src/index.crates.io/glob-0.3.3/Cargo.toml \
        CARGO_PKG_AUTHORS=The' Rust Project Developers' \
        CARGO_PKG_DESCRIPTION=Support' for matching file paths against Unix shell style patterns.\
' \
        CARGO_PKG_HOMEPAGE=https'://github.com/rust-lang/glob' \
        CARGO_PKG_LICENSE=MIT' OR Apache-2.0' \
        CARGO_PKG_LICENSE_FILE= \
        CARGO_PKG_NAME=glob \
        CARGO_PKG_README=README.md \
        CARGO_PKG_REPOSITORY=https'://github.com/rust-lang/glob' \
        CARGO_PKG_RUST_VERSION=1.63.0 \
        CARGO_PKG_VERSION=0.3.3 \
        CARGO_PKG_VERSION_MAJOR=0 \
        CARGO_PKG_VERSION_MINOR=3 \
        CARGO_PKG_VERSION_PATCH=3 \
        CARGO_PKG_VERSION_PRE= \
        CARGOGREEN=1 \
      rustc --cap-lints warn --check-cfg cfg'(docsrs,test)' --check-cfg cfg'(feature, values())' --crate-name glob --crate-type lib --edition 2015 --emit dep-info,metadata,link --error-format json --json diagnostic-rendered-ansi,artifacts,future-incompat --out-dir /target/release/deps -C embed-bitcode'=no' -C extra-filename'=-e8a15153c90a7f99' -C metadata'=93ae41652b2e9f0b' -C overflow-checks'=off' -C strip'=debuginfo' -L dependency'=/target/release/deps' $CARGO_HOME/registry/src/index.crates.io/glob-0.3.3/src/lib.rs \
        1>          ./out-e8a15153c90a7f99-stdout \
        2>          ./out-e8a15153c90a7f99-stderr \
        || echo $? >./out-e8a15153c90a7f99-errcode\
  ; find ./*-e8a15153c90a7f99* -exec touch --no-dereference --date=@$SOURCE_DATE_EPOCH '{}' + \
 || echo $? >./out-e8a15153c90a7f99-errcode
FROM scratch AS out-e8a15153c90a7f99
COPY --link --from=dep-n-glob-0.3.3-e8a15153c90a7f99 /target/release/deps/*-e8a15153c90a7f99* /

FROM scratch AS cratesio-fontsan-0.6.1
ADD --chmod=0664 --unpack --checksum=sha256:52fd401b496627c46f35318272508fcdcb77927868507ed2ad796408aa903923 \
  https://static.crates.io/crates/fontsan/fontsan-0.6.1.crate /
FROM rust-base AS dep-x-fontsan-0.6.1-0c6cadf33ea8b941
WORKDIR /target/release/build/fontsan-0c6cadf33ea8b941
RUN \
  --mount=from=cratesio-fontsan-0.6.1,source=/fontsan-0.6.1,dst=$CARGO_HOME/registry/src/index.crates.io/fontsan-0.6.1 \
  --mount=from=out-6c6b7b88f024f856,dst=/target/release/deps/libcc-6c6b7b88f024f856.rlib,source=/libcc-6c6b7b88f024f856.rlib \
  --mount=from=out-03bc48596003a6dc,dst=/target/release/deps/libfind_msvc_tools-03bc48596003a6dc.rlib,source=/libfind_msvc_tools-03bc48596003a6dc.rlib \
  --mount=from=out-4ba22a5c4650f7d6,dst=/target/release/deps/liblibc-4ba22a5c4650f7d6.rlib,source=/liblibc-4ba22a5c4650f7d6.rlib \
  --mount=from=out-9de29d5c7086d65d,dst=/target/release/deps/libjobserver-9de29d5c7086d65d.rlib,source=/libjobserver-9de29d5c7086d65d.rlib \
  --mount=from=out-3b266231d4b893c0,dst=/target/release/deps/libshlex-3b266231d4b893c0.rlib,source=/libshlex-3b266231d4b893c0.rlib \
  --mount=from=out-e8a15153c90a7f99,dst=/target/release/deps/libglob-e8a15153c90a7f99.rlib,source=/libglob-e8a15153c90a7f99.rlib \
    env CARGO_CRATE_NAME=build_script_build \
        CARGO_INCREMENTAL=0 \
        CARGO_MANIFEST_DIR=$CARGO_HOME/registry/src/index.crates.io/fontsan-0.6.1 \
        CARGO_MANIFEST_PATH=$CARGO_HOME/registry/src/index.crates.io/fontsan-0.6.1/Cargo.toml \
        CARGO_PKG_AUTHORS=The' Servo Project Developers' \
        CARGO_PKG_DESCRIPTION=Sanitiser' for untrusted font files' \
        CARGO_PKG_HOMEPAGE= \
        CARGO_PKG_LICENSE=BSD-3-Clause \
        CARGO_PKG_LICENSE_FILE= \
        CARGO_PKG_NAME=fontsan \
        CARGO_PKG_README=README.md \
        CARGO_PKG_REPOSITORY=https'://github.com/servo/fontsan' \
        CARGO_PKG_RUST_VERSION= \
        CARGO_PKG_VERSION=0.6.1 \
        CARGO_PKG_VERSION_MAJOR=0 \
        CARGO_PKG_VERSION_MINOR=6 \
        CARGO_PKG_VERSION_PATCH=1 \
        CARGO_PKG_VERSION_PRE= \
        CARGOGREEN=1 \
      rustc --cap-lints warn --cfg feature'="default"' --cfg feature'="libz-sys"' --check-cfg cfg'(docsrs,test)' --check-cfg cfg'(feature, values("default", "libz-rs", "libz-sys"))' --crate-name build_script_build --crate-type bin --edition 2015 --emit dep-info,link --error-format json --extern cc'=/target/release/deps/libcc-6c6b7b88f024f856.rlib' --extern glob'=/target/release/deps/libglob-e8a15153c90a7f99.rlib' --json diagnostic-rendered-ansi,artifacts,future-incompat --out-dir /target/release/build/fontsan-0c6cadf33ea8b941 -C embed-bitcode'=no' -C extra-filename'=-0c6cadf33ea8b941' -C metadata'=470111de70ff3671' -C overflow-checks'=off' -C strip'=debuginfo' -L dependency'=/target/release/deps' $CARGO_HOME/registry/src/index.crates.io/fontsan-0.6.1/build.rs \
        1>          ./out-0c6cadf33ea8b941-stdout \
        2>          ./out-0c6cadf33ea8b941-stderr \
        || echo $? >./out-0c6cadf33ea8b941-errcode\
  ; mv ./build_script_build-0c6cadf33ea8b941 ./_build_script_build-0c6cadf33ea8b941 \
 && printf '#!/bin/sh\nenv CARGOGREEN_EXECUTE_BUILDRS_=$0 cargo-green\n' >./build_script_build-0c6cadf33ea8b941 \
 && chmod +x ./build_script_build-0c6cadf33ea8b941 \
 || echo $? >./out-0c6cadf33ea8b941-errcode \
  ; find ./* -exec touch --no-dereference --date=@$SOURCE_DATE_EPOCH '{}' + \
 || echo $? >./out-0c6cadf33ea8b941-errcode
FROM scratch AS out-0c6cadf33ea8b941
COPY --link --from=dep-x-fontsan-0.6.1-0c6cadf33ea8b941 /target/release/build/fontsan-0c6cadf33ea8b941/*-0c6cadf33ea8b941* /

FROM rust-base AS run-z-fontsan-0.6.1-6164618af35a3225
WORKDIR /target/release/build/fontsan-6164618af35a3225/out
WORKDIR $CARGO_HOME/registry/src/index.crates.io/fontsan-0.6.1
RUN \
  --mount=from=out-0c6cadf33ea8b941,source=/_build_script_build-0c6cadf33ea8b941,dst=/target/release/build/fontsan-0c6cadf33ea8b941/build-script-build \
  --mount=from=cratesio-fontsan-0.6.1,source=/fontsan-0.6.1,dst=$CARGO_HOME/registry/src/index.crates.io/fontsan-0.6.1 \
    env CARGO_CFG_DEBUG_ASSERTIONS= \
        CARGO_CFG_FEATURE=default,libz-sys \
        CARGO_CFG_PANIC=unwind \
        CARGO_CFG_TARGET_ABI= \
        CARGO_CFG_TARGET_ARCH=x86_64 \
        CARGO_CFG_TARGET_ENDIAN=little \
        CARGO_CFG_TARGET_ENV=gnu \
        CARGO_CFG_TARGET_FAMILY=unix \
        CARGO_CFG_TARGET_FEATURE=fxsr,sse,sse2 \
        CARGO_CFG_TARGET_HAS_ATOMIC=16,32,64,8,ptr \
        CARGO_CFG_TARGET_OS=linux \
        CARGO_CFG_TARGET_POINTER_WIDTH=64 \
        CARGO_CFG_TARGET_VENDOR=unknown \
        CARGO_CFG_UNIX= \
        CARGO_ENCODED_RUSTFLAGS= \
        CARGO_FEATURE_DEFAULT=1 \
        CARGO_FEATURE_LIBZ_SYS=1 \
        CARGO_INCREMENTAL=0 \
        CARGO_MANIFEST_DIR=$CARGO_HOME/registry/src/index.crates.io/fontsan-0.6.1 \
        CARGO_MANIFEST_PATH=$CARGO_HOME/registry/src/index.crates.io/fontsan-0.6.1/Cargo.toml \
        CARGO_PKG_AUTHORS=The' Servo Project Developers' \
        CARGO_PKG_DESCRIPTION=Sanitiser' for untrusted font files' \
        CARGO_PKG_HOMEPAGE= \
        CARGO_PKG_LICENSE=BSD-3-Clause \
        CARGO_PKG_LICENSE_FILE= \
        CARGO_PKG_NAME=fontsan \
        CARGO_PKG_README=README.md \
        CARGO_PKG_REPOSITORY=https'://github.com/servo/fontsan' \
        CARGO_PKG_RUST_VERSION= \
        CARGO_PKG_VERSION=0.6.1 \
        CARGO_PKG_VERSION_MAJOR=0 \
        CARGO_PKG_VERSION_MINOR=6 \
        CARGO_PKG_VERSION_PATCH=1 \
        CARGO_PKG_VERSION_PRE= \
        DEBUG=false \
        DEP_WOFF2_INCLUDE_DIR=$CARGO_HOME/registry/src/index.crates.io/fontsan-woff2-0.1.1/include \
        DEP_Z_INCLUDE=/usr/include \
        HOST=x86_64-unknown-linux-gnu \
        NUM_JOBS=1 \
        OPT_LEVEL=3 \
        OUT_DIR=/target/release/build/fontsan-6164618af35a3225/out \
        PROFILE=release \
        RUSTDOC=$RUSTUP_HOME/toolchains/1.94.0-x86_64-unknown-linux-gnu/bin/rustdoc \
        TARGET=x86_64-unknown-linux-gnu \
        CARGOGREEN=1 \
      /target/release/build/fontsan-0c6cadf33ea8b941/build-script-build \
        1>          /target/release/build/fontsan-6164618af35a3225/out/out-6164618af35a3225-stdout \
        2>          /target/release/build/fontsan-6164618af35a3225/out/out-6164618af35a3225-stderr \
        || echo $? >/target/release/build/fontsan-6164618af35a3225/out/out-6164618af35a3225-errcode\
  ; find /target/release/build/fontsan-6164618af35a3225/out/* -exec touch --no-dereference --date=@$SOURCE_DATE_EPOCH '{}' + \
 || echo $? >/target/release/build/fontsan-6164618af35a3225/out/out-6164618af35a3225-errcode
FROM scratch AS out-6164618af35a3225
COPY --link --from=run-z-fontsan-0.6.1-6164618af35a3225 /target/release/build/fontsan-6164618af35a3225/out /

# Pipe this file to:
# DOCKER_BUILDKIT="1" \
#   docker build --output=. - <THIS_FILE

FROM scratch
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-avar.o /3e3b30a1b362905a-avar.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-cff.o /3e3b30a1b362905a-cff.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-cff_charstring.o /3e3b30a1b362905a-cff-charstring.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-cmap.o /3e3b30a1b362905a-cmap.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-colr.o /3e3b30a1b362905a-colr.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-cpal.o /3e3b30a1b362905a-cpal.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-cvar.o /3e3b30a1b362905a-cvar.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-cvt.o /3e3b30a1b362905a-cvt.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-feat.o /3e3b30a1b362905a-feat.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-fpgm.o /3e3b30a1b362905a-fpgm.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-fvar.o /3e3b30a1b362905a-fvar.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-gasp.o /3e3b30a1b362905a-gasp.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-gdef.o /3e3b30a1b362905a-gdef.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-glat.o /3e3b30a1b362905a-glat.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-gloc.o /3e3b30a1b362905a-gloc.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-glyf.o /3e3b30a1b362905a-glyf.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-gpos.o /3e3b30a1b362905a-gpos.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-gsub.o /3e3b30a1b362905a-gsub.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-gvar.o /3e3b30a1b362905a-gvar.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-hdmx.o /3e3b30a1b362905a-hdmx.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-head.o /3e3b30a1b362905a-head.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-hhea.o /3e3b30a1b362905a-hhea.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-hvar.o /3e3b30a1b362905a-hvar.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-kern.o /3e3b30a1b362905a-kern.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-layout.o /3e3b30a1b362905a-layout.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-loca.o /3e3b30a1b362905a-loca.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-ltsh.o /3e3b30a1b362905a-ltsh.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-math.o /3e3b30a1b362905a-math.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-maxp.o /3e3b30a1b362905a-maxp.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-metrics.o /3e3b30a1b362905a-metrics.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-mvar.o /3e3b30a1b362905a-mvar.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-name.o /3e3b30a1b362905a-name.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-os2.o /3e3b30a1b362905a-os2.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-post.o /3e3b30a1b362905a-post.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-prep.o /3e3b30a1b362905a-prep.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-sile.o /3e3b30a1b362905a-sile.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-silf.o /3e3b30a1b362905a-silf.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-sill.o /3e3b30a1b362905a-sill.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-stat.o /3e3b30a1b362905a-stat.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-variations.o /3e3b30a1b362905a-variations.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-vdmx.o /3e3b30a1b362905a-vdmx.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-vhea.o /3e3b30a1b362905a-vhea.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-vorg.o /3e3b30a1b362905a-vorg.o
COPY --link --from=out-6164618af35a3225 /3e3b30a1b362905a-vvar.o /3e3b30a1b362905a-vvar.o
COPY --link --from=out-6164618af35a3225 /c71c4d9ddcf5f01c-lz4.o /c71c4d9ddcf5f01c-lz4.o
COPY --link --from=out-6164618af35a3225 /liblz4.a /liblz4.a
