#!/bin/bash -eux
set -o pipefail

CARGO=${CARGO:-cargo}

$CARGO install --locked --frozen --offline --force --path cargo-green/

install_package=buildxargs@1.4.0
install_root=$(mktemp -d)

export CARGOGREEN_FINAL_PATH=./hack/$install_package.Dockerfile
export RUSTCBUILDX_SYNTAX=docker-image://docker.io/docker/dockerfile:1@sha256:4c68376a702446fc3c79af22de146a148bc3367e73c25a5803d453b6b3f722fb # TODO: change env name
export CARGOGREEN_BASE_IMAGE=docker-image://docker.io/library/rust:1.84.1-slim@sha256:69fbd6ab81b514580bc14f35323fecb09feba9e74c5944ece9a70d9a2a369df0
export CARGOGREEN_LOG=trace
export RUSTCBUILDX_LOG_PATH=$(mktemp) #TODO: change env name to CARGOGREEN_LOG_PATH
export CARGO_TARGET_DIR=$(mktemp -d /tmp/hack-caching--XXXXXXX)

$CARGO green supergreen env #TODO: change env names

git rm -f $CARGOGREEN_FINAL_PATH 2>/dev/null 1>&2 || true

strip_versioning_from_final_path() {
	cat $CARGOGREEN_FINAL_PATH | grep -vF 'Generated by https://github.com/fenollp/supergreen' >$CARGOGREEN_FINAL_PATH. && mv $CARGOGREEN_FINAL_PATH. $CARGOGREEN_FINAL_PATH
}
compute_installed_bin_hash() {
	sha256sum $install_root/bin/${install_package%@*} | awk '{print $1}'
}
ensure__rewrite_cratesio_index__works() {
	! grep -F '/index.crates.io-' $RUSTCBUILDX_LOG_PATH | grep -vE '/index.crates.io-0{16}|original args|env is set|opening .RO. crate tarball|picked'
}

echo Sortons nos cartes!
echo


#---


rm -rf $CARGO_TARGET_DIR/* >/dev/null
$CARGO green install --locked                            $install_package --root=$install_root
strip_versioning_from_final_path
git add $CARGOGREEN_FINAL_PATH
ensure__rewrite_cratesio_index__works
install_sha=$(compute_installed_bin_hash)

grep -A2 '# Pipe this file to:' $CARGOGREEN_FINAL_PATH
echo Builds fine
echo


#---


rm -f $CARGO_TARGET_DIR/release/deps/${install_package%@*}-????????????????
$(tail -n1 $CARGOGREEN_FINAL_PATH | cut -c2-) <$CARGOGREEN_FINAL_PATH
[[ $install_sha = $(sha256sum $CARGO_TARGET_DIR/release/deps/${install_package%@*}-???????????????? | awk '{print $1}') ]] # rebuild => no change

echo Builds fine and in a standalone way
echo


#---


export CARGOGREEN_BASE_IMAGE=docker-image://docker.io/library/rust:1.84.0-slim@sha256:0ec205a9abb049604cb085f2fdf7630f1a31dad1f7ad4986154a56501fb7ca77

rm -rf $CARGO_TARGET_DIR/* >/dev/null
$CARGO green install --locked --frozen --offline --force $install_package --root=$install_root
strip_versioning_from_final_path
git --no-pager diff -- $CARGOGREEN_FINAL_PATH
cat <<'EOF' | diff -u <(git --no-pager diff -- $CARGOGREEN_FINAL_PATH | tail -n +6) -
 # syntax=docker.io/docker/dockerfile:1@sha256:4c68376a702446fc3c79af22de146a148bc3367e73c25a5803d453b6b3f722fb
 # check=error=true
-FROM --platform=$BUILDPLATFORM docker.io/library/rust:1.84.1-slim@sha256:69fbd6ab81b514580bc14f35323fecb09feba9e74c5944ece9a70d9a2a369df0 AS rust-base
+FROM --platform=$BUILDPLATFORM docker.io/library/rust:1.84.0-slim@sha256:0ec205a9abb049604cb085f2fdf7630f1a31dad1f7ad4986154a56501fb7ca77 AS rust-base
 
 FROM scratch AS cratesio-pico-args-0.5.0
 ADD --chmod=0664 --checksum=sha256:5be167a7af36ee22fe3115051bc51f6e6c7054c9348e28deb4f49bd6f705a315 \
EOF
git add $CARGOGREEN_FINAL_PATH
ensure__rewrite_cratesio_index__works
[[ $install_sha != $(compute_installed_bin_hash) ]] # change rustc => change final bin
install_sha=$(compute_installed_bin_hash)

echo Changing rustc does not change crates metadata
echo


#---


# Adding -vv => s/'--cap-lints' 'allow'/'--cap-lints' 'warn'/g
# Adding +nightly => changes '-C' 'metadata=' and '-C' 'extra-filename='
# Changing CARGOGREEN_LOG_LEVEL shouldn't evict cache

# rm -rf $CARGO_TARGET_DIR/* >/dev/null
# $CARGO green +nightly install --locked --frozen --offline --force $install_package --root=$install_root
# strip_versioning_from_final_path
# git --no-pager diff --color-words=. --exit-code -- $CARGOGREEN_FINAL_PATH


#---


export CARGO_TARGET_DIR=$(mktemp -d /tmp/hack-caching--XXXXXXX)

rm -rf $CARGO_TARGET_DIR/* >/dev/null
$CARGO green install --locked --frozen --offline --force $install_package --root=$install_root
strip_versioning_from_final_path
ensure__rewrite_cratesio_index__works
[[ $install_sha = $(compute_installed_bin_hash) ]] # change targetdir => no binary changes

echo Changing CARGO_TARGET_DIR tho.... TODO: replace target dir in final path with e.g. /target/ or '/target/$target_triple/'
echo

git --no-pager diff --color-words=. -- $CARGOGREEN_FINAL_PATH


#---
git rm -f $CARGOGREEN_FINAL_PATH
echo
! grep -Ei '[t]odo|[f]ixme' $0
