#!/bin/bash -eux
set -o pipefail

CARGO=${CARGO:-cargo}

$CARGO install --locked --force --path cargo-green/

install_package=buildxargs@1.4.0
install_root=$(mktemp -d)

export CARGOGREEN_FINAL_PATH=./recipes/$install_package.Dockerfile
export CARGOGREEN_SYNTAX=docker-image://docker.io/docker/dockerfile:1@sha256:4c68376a702446fc3c79af22de146a148bc3367e73c25a5803d453b6b3f722fb
export CARGOGREEN_BASE_IMAGE=docker-image://docker.io/library/rust:1.84.1-slim@sha256:69fbd6ab81b514580bc14f35323fecb09feba9e74c5944ece9a70d9a2a369df0
export CARGOGREEN_LOG=trace
export CARGOGREEN_LOG_PATH=/tmp/cargo-green--hack-caching--$install_package.log
export CARGO_TARGET_DIR=/tmp/cargo-green--hack-caching--target-dir
mkdir -p $CARGO_TARGET_DIR
rm -rf $CARGO_TARGET_DIR/*

$CARGO green supergreen env

compute_installed_bin_sha256() {
	sha256sum $install_root/bin/${install_package%@*} | awk '{print $1}'
}
ensure__rewrite_cratesio_index__works() {
	! grep -F '/index.crates.io-' $CARGOGREEN_LOG_PATH | grep -vE '/index.crates.io-0{16}|original args|env is set|opening .RO. crate tarball|picked'
}

echo Sortons nos cartes!
echo


#---


rm -rf $CARGO_TARGET_DIR/* >/dev/null
$CARGO green install --locked                            $install_package --root=$install_root
git add $CARGOGREEN_FINAL_PATH
ensure__rewrite_cratesio_index__works
$install_root/bin/${install_package%@*} --help >/dev/null
install_sha=$(compute_installed_bin_sha256)

grep -A2 '# Pipe this file to:' $CARGOGREEN_FINAL_PATH
echo Builds fine
echo


#---


rm $CARGO_TARGET_DIR/release/deps/${install_package%@*}-????????????????
invocation=$(tail -n1 $CARGOGREEN_FINAL_PATH | cut -c2-)
$invocation --call=check   <$CARGOGREEN_FINAL_PATH
$invocation --call=outline <$CARGOGREEN_FINAL_PATH
$invocation --call=targets <$CARGOGREEN_FINAL_PATH
$invocation                <$CARGOGREEN_FINAL_PATH
$CARGO_TARGET_DIR/release/deps/${install_package%@*}-???????????????? --help >/dev/null
[[ $install_sha = $(sha256sum $CARGO_TARGET_DIR/release/deps/${install_package%@*}-???????????????? | awk '{print $1}') ]] # rebuild => no change

echo Builds fine and in a standalone way
echo


#---


export CARGOGREEN_BASE_IMAGE=docker-image://docker.io/library/rust:1.84.0-slim@sha256:0ec205a9abb049604cb085f2fdf7630f1a31dad1f7ad4986154a56501fb7ca77

rm -rf $CARGO_TARGET_DIR/* >/dev/null
$CARGO green install --locked --frozen --offline --force $install_package --root=$install_root
REPO=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[] | select(.name=="cargo-green").repository')
VSN=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[] | select(.name=="cargo-green").version')
git --no-pager diff -- $CARGOGREEN_FINAL_PATH
cat <<EOF | diff -u - <(git --no-pager diff -- $CARGOGREEN_FINAL_PATH | tail -n+6)
 # check=error=true
 # Generated by $REPO v$VSN
 
-FROM --platform=\$BUILDPLATFORM docker.io/library/rust:1.84.1-slim@sha256:69fbd6ab81b514580bc14f35323fecb09feba9e74c5944ece9a70d9a2a369df0 AS rust-base
+FROM --platform=\$BUILDPLATFORM docker.io/library/rust:1.84.0-slim@sha256:0ec205a9abb049604cb085f2fdf7630f1a31dad1f7ad4986154a56501fb7ca77 AS rust-base
 
 FROM scratch AS cratesio-pico-args-0.5.0
 ADD --chmod=0664 --checksum=sha256:5be167a7af36ee22fe3115051bc51f6e6c7054c9348e28deb4f49bd6f705a315 \\
@@ -183,7 +183,7 @@ COPY --from=dep-b-buildxargs-1.4.0-39127c16f4d70192 /tmp/cargo-green--hack-cachi
 ## 
 ## [[stages]]
 ## name = "rust-base"
-## script = "FROM --platform=\$BUILDPLATFORM docker.io/library/rust:1.84.1-slim@sha256:69fbd6ab81b514580bc14f35323fecb09feba9e74c5944ece9a70d9a2a369df0 AS rust-base"
+## script = "FROM --platform=\$BUILDPLATFORM docker.io/library/rust:1.84.0-slim@sha256:0ec205a9abb049604cb085f2fdf7630f1a31dad1f7ad4986154a56501fb7ca77 AS rust-base"
 ## 
 ## [[stages]]
 ## name = "cratesio-buildxargs-1.4.0"
EOF
git add $CARGOGREEN_FINAL_PATH
ensure__rewrite_cratesio_index__works
$install_root/bin/${install_package%@*} --help >/dev/null
[[ $install_sha != $(compute_installed_bin_sha256) ]] # change rustc => change final bin
install_sha=$(compute_installed_bin_sha256)

# https://github.com/rust-lang/cargo/issues/10367#issuecomment-1053678306
# > This is currently intentional behavior. There are situations where RUSTC changes, but we don't want that to trigger a full recompile. If one rustc emits the same version output as another, then cargo assumes they essentially behave the same, even if they are from different paths. I'm not sure this is something that can be changed without causing unwanted recompiles in some situations.
#=> no changes to final path (except for that base image)

echo Changing rustc does not change crates metadata
echo


#---


# Adding -vv => s/'--cap-lints' 'allow'/'--cap-lints' 'warn'/g
# TODO: cargo -vv test != cargo test: => the rustc flags will change => Dockerfile needs new cache key
# => otherwise docker builder cache won't have the correct hit
# https://rustc-dev-guide.rust-lang.org/backend/libs-and-metadata.html
#=> a filename suffix with content hash?

# Adding +nightly => changes '-C' 'metadata=' and '-C' 'extra-filename='
# Changing CARGOGREEN_LOG_LEVEL shouldn't evict cache

# rm -rf $CARGO_TARGET_DIR/* >/dev/null
# $CARGO green +nightly install --locked --frozen --offline --force $install_package --root=$install_root
# git --no-pager diff --color-words=. --exit-code -- $CARGOGREEN_FINAL_PATH


#---


old_target_dir=$CARGO_TARGET_DIR
rm -rf $old_target_dir/* >/dev/null
export CARGO_TARGET_DIR=/tmp/cargo-green--hack-caching
mkdir -p $CARGO_TARGET_DIR

rm -rf $CARGO_TARGET_DIR/* >/dev/null
$CARGO green install --locked --frozen --offline --force $install_package --root=$install_root
#TODO: rewrite target dir between host and build(..) calls
# git --no-pager diff -- $CARGOGREEN_FINAL_PATH
# cat <<'EOF' | diff -u - <(git --no-pager diff -- $CARGOGREEN_FINAL_PATH | tail -n+7)
#  # Pipe this file to:
#  # DOCKER_BUILDKIT="1" \
# -#   docker --debug build --network=none --platform=local --pull=false --target=out-68f2214769fd28b1 --output=type=local,dest=/tmp/cargo-green--hack-caching--target-dir/release/deps -
# +#   docker --debug build --network=none --platform=local --pull=false --target=out-68f2214769fd28b1 --output=type=local,dest=/tmp/cargo-green--hack-caching/release/deps -
# EOF
unset old_target_dir
ensure__rewrite_cratesio_index__works
$install_root/bin/${install_package%@*} --help >/dev/null
[[ $install_sha = $(compute_installed_bin_sha256) ]] # change targetdir => no binary changes
# git --no-pager diff -- $CARGOGREEN_FINAL_PATH
git add $CARGOGREEN_FINAL_PATH

echo Changing CARGO_TARGET_DIR tho.... TODO: replace target dir in final path with e.g. /target/ or '/target/$target_triple/'
echo
