#!/bin/bash -eu
set -o pipefail

branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
runID=$(gh run list --branch "$branch" --limit 1 --workflow CLIs --json databaseId --jq '.[].databaseId')
gh run download "$runID" --pattern '*.Dockerfile'

for f in *.Dockerfile/*.Dockerfile; do
	echo $f
	mv $f recipes/
	rmdir $(dirname $f)
	f=recipes/$(basename $f)

	if git --no-pager diff --exit-code -I '^# Generated by' -I ' AS rust-base$' -I '^# syntax=docker.io/docker/dockerfile:1@' -- $f; then
		git checkout -- $f
	fi
done
