#!/usr/bin/env -S bash -eu
set -o pipefail

branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
runID=$(gh run list --branch "$branch" --limit 1 --workflow CLIs --json databaseId --jq '.[].databaseId')
gh run download "$runID" --pattern '*.Dockerfile'

for f in *.Dockerfile/*.Dockerfile; do
	echo $f
	mv $f recipes/
	rmdir $(dirname $f)
	f=recipes/$(basename $f)

	# When diffing, ignore changes that:
	#  mention the crate version number
	#  mention the rustc version number
	#  mention BuildKit syntax version
	#  and changes to cargo JSON stderr messages. (TODO: drop) Turns out these are flaky though multiple builds...
	if git --no-pager diff --exit-code \
		--ignore-matching-lines='^# Generated by' \
		--ignore-matching-lines=' AS rust-base$' \
		--ignore-matching-lines='^# syntax=docker.io/docker/dockerfile:1@' \
		--ignore-matching-lines="^##     '\{" \
		-- $f; then
		git checkout -- $f || continue
	fi
done
