use anyhow::{Result, anyhow};
use camino::Utf8Path;
use log::{info, trace};

use crate::{REPO, VSN, dirs::hash, image_uri::ImageUri, logging::maybe_log, sys::sys};

pub(crate) struct Containerfile {
    script: String,
}

impl Containerfile {
    #[must_use]
    pub(crate) fn with_syntax(syntax: &ImageUri) -> Self {
        let mut header = format!("# syntax={}\n", syntax.noscheme());
        header.push_str("# check=error=true\n");
        header.push_str(&format!("# Generated by {REPO} v{VSN}\n"));
        header.push('\n');
        Self { script: header }
    }

    pub(crate) fn push(&mut self, block: &str) {
        self.script.push_str(block);
    }

    pub(crate) fn pushln(&mut self, block: &str) {
        self.push(block);
        self.nl()
    }

    pub(crate) fn nl(&mut self) {
        self.script.push('\n');
    }

    #[must_use]
    pub(crate) fn hashed(&self) -> String {
        hash(&self.script)
    }

    #[must_use]
    pub(crate) fn as_str(&self) -> &str {
        &self.script
    }

    pub(crate) fn write_to(&self, path: &Utf8Path) -> Result<()> {
        info!("opening (RW) containerfile {path}");
        sys().fs.write(path, self.as_str()).map_err(|e| anyhow!("Failed creating {path}: {e}"))?;

        if maybe_log().is_some() {
            info!("dockerfile: {path}");
            match sys().fs.read_to_string(path) {
                Ok(data) => data,
                Err(e) => format!("Failed reading {path}: {e}"),
            }
            .lines()
            .filter(|x| !x.is_empty())
            .for_each(|line| trace!("❯ {line}"));
        }

        Ok(())
    }
}

#[cfg(test)]
/// [`snapbox::assert_data_eq!`] with path normalization off.
///
/// Containerfiles are full of `\` line continuations, which snapbox would otherwise
/// rewrite to `/` as if they were Windows path separators, so every `RUN` line would
/// compare equal no matter which one it was.
///
/// Like the macro it wraps, `SNAPSHOTS=overwrite` updates the inline `str![[…]]`.
macro_rules! assert_containerfile_eq {
    ($actual:expr, $expected:expr $(,)?) => {{
        let actual = ::snapbox::IntoData::into_data($actual);
        let expected = ::snapbox::IntoData::into_data($expected);
        ::snapbox::Assert::new()
            .action_env(::snapbox::assert::DEFAULT_ACTION_ENV)
            .normalize_paths(false)
            .eq(actual, expected);
    }};
}

#[cfg(test)]
pub(crate) use assert_containerfile_eq;
